### PR TITLE
Take work phone out of member forms.

### PR DESCRIPTION
**Pull request by ivan-unfolds**

### CODE REVIEW

**Comment by sofer** [comment]
https://www.pivotaltracker.com/story/show/129787477

**Comment by rjmk** [comment]
Simple enough. Do we want to drop it from the model as well?

**Comment by ivan-unfolds** [comment]
@rjmk have taken work phone out of various places. Should I have taken it out of the blueprint?

**Comment by rjmk** [comment]
You should set `remove` to `true` in the blueprint

**Comment by ivan-unfolds** [comment]
@rjmk have changed the blueprint now.

**Comment by rjmk** [comment]
👍

**Pull request merged**
