### PR TITLE
Change labels print styling.

### PR DESCRIPTION
**Pull request by ivan-unfolds**

### CODE REVIEW

**Comment by rjmk** [comment]
@ivanmauricio Might we have to worry about the autoresizing? https://github.com/foundersandcoders/sail-back/blob/e5576b6c51f6a6473272fb83241dec407a8211e3/src/admin/containers/labels.js#L39-L40

**Comment by ivan-unfolds** [comment]
@rjmk that functionality was not actually making a difference in the print view so I took it out.

**Comment by rjmk** [comment]
@ivanmauricio Are you sure? If you look at the labels on the live site, I think it is

**Comment by ivan-unfolds** [comment]
@rjmk On the webview it does, but the font-size is the same for all labels when looked at on print preview. I think...

**Comment by ivan-unfolds** [comment]
@rjmk I guess because it makes the webview look better, I should just leave it in?

**Comment by rjmk** [comment]
I think it might end up making a difference on the print view if it were sufficiently long. Either way, seems like we probably don't need to tweak it, so let's leave it in 👍

**Pull request closed without merging**
