### PR TITLE
Letter bugs fixed

### PR DESCRIPTION
**Pull request by ivan-unfolds**
- [x]  Letters recipients has 'undefined' in it occasionally
- [ ]  Everyone is said to be owing '£0.00' -> hopefully to be fixed upon updating db
- [x]  due date showing up as null on heroku -> we have made an issue on gh
- [x]  Printing Spacing

### CODE REVIEW

**Comment by rjmk** [comment]
Adding `display: inline-block` to the print style for `.letter-page` seems to fix the breaking letters issue

**Comment by jay-meister** [comment]
Thanks Rafe, will check it over before lunch. Any success with the £0.00 on the letters?

**Comment by rjmk** [comment]
Should be resolved by the refreshing the db (after updating upload scripts)

**Comment by rjmk** [comment]
Wizardry. Thanks guys

**Pull request merged**
