### PR TITLE
WIP fixing gift-aid-signed

### PR DESCRIPTION
**Pull request by rjmk**
This stops the issue with gift aid signed not displaying.

Need to work out how we're handling the date changes and so on

### CODE REVIEW

**Comment by ivan-unfolds** [comment]
@rjmk This looks good. Should we go ahead and merge and I will start working on displaying date fields on separate branch?

**Comment by rjmk** [comment]
Try setting a members gift_aid_signed to true. The error messages on the dates are unfriendly. Let's fix that first!

**Comment by ivan-unfolds** [comment]
@rjmk This works. What do you think?

**Comment by rjmk** [comment]
Awesome, @ivanmauricio

**Pull request merged**
