### PR TITLE
fix bootstrap changes

### PR DESCRIPTION
**Pull request by rjmk**
@ivanmauricio @JMurphyWeb I've stuck a few things in here which by rights don't belong! 

The important stuff is to do with the change of the class 'label' which bootstrap uses. Do you guys know of any list of classes bootstrap claims?

### CODE REVIEW

**Comment by ivan-unfolds** [comment]
@rjmk I think this might be all the classes that bootstrap uses - https://bootstrapcreative.com/resources/bootstrap-3-css-classes-index/ https://bootstrapcreative.com/resources/bootstrap-3-css-classes-index/. Also I cannot start the admin view after these changes. The user side works fine. Any ideas?

**Comment by ivan-unfolds** [comment]
I cannot start it locally. On the live site everything appears to be working fine.

**Comment by rjmk** [comment]
Hey @ivanmauricio, when you say you can't start it, do you mean you see a blank page when you log in? Are there errors in the console? If 'yes' and 'no' respectively, I think you just need to wait a bit for the bundle to finish being constructed

**Comment by rjmk** [comment]
I also found [this](https://gist.github.com/geksilla/6543145) plain text list. We can hopefully use that to search our CSS for any classes likely to cause us problems

**Comment by ivan-unfolds** [comment]
Just a blank page on admin side. Do get an error however, it says cannot module 298, which I think may be react-dom. Also is there a problem in views/includes/_scripts.swig? There is the end of a comment which is still there, i.e. —>.

**Comment by rjmk** [comment]
Are you using `npm run dev` instead of `npm start`?

**Comment by ivan-unfolds** [comment]
Thanks Rafe, it works with npm start. We have been using npm run dev up until now. Do we have to use npm start now? If so, does that mean we have to rebuild after every change?

**Comment by rjmk** [comment]
Currently the app only works with `npm start` and requires rebuilding. I will push to a new branch where it works with `npm run dev`

**Comment by rjmk** [comment]
Done

**Pull request merged**
