### PR TITLE
Delete unused styles from assets

### PR DESCRIPTION
**Pull request by ivan-unfolds**

### CODE REVIEW

**Comment by ivan-unfolds** [comment]
@rjmk can we also delete the target folder?

**Comment by rjmk** [comment]
@ivanmauricio Which folder?

**Comment by ivan-unfolds** [comment]
@rjmk my bad, I think I had just put a random folder in my sail_back directory. Bit confused about why git was not tracking it though.

**Comment by rjmk** [comment]
@ivanmauricio Git tracks files not folders, so if the folder was empty, it didn't exist to git

**Pull request merged**
