### PR TITLE
Document backup

### PR DESCRIPTION
**Pull request by jay-meister**
add documentation for restoring from backup

### CODE REVIEW

**Comment by jay-meister** [comment]
@mantagen left the following comment https://github.com/foundersandcoders/sail-back/pull/488#pullrequestreview-28265916

This PR is just cleaned up version without the travis debug attempts.

**Comment by jay-meister** [comment]
@mantagen merge if happy please

**Comment by jay-meister** [comment]
Merging.

**Comment by mantagen** [comment]
This looks ace :+1:

**Pull request merged**
