### PR TITLE
Braintree Implementation

### PR DESCRIPTION
**Pull request by ivan-unfolds**
@besarthoxhaj This is not ready to be merged in yet. Would love for you to have a look at what @JMurphyWeb and I have been up to though, and critique the hell out of it 😈

### CODE REVIEW

**Comment by besarthoxhaj** [comment]
@ivanmauricio @JMurphyWeb great will have a look!:)

Knowing the expected behavior through some tests would help me massively, though:)

**Comment by jay-meister** [comment]
@ivanmauricio is going to add some tests for your pleasure @besarthoxhaj

**Comment by besarthoxhaj** [comment]
Super!

**Comment by ivan-unfolds** [comment]
@besarthoxhaj Ready for your consideration 😄

**Pull request merged**
