### PR TITLE
lays groundwork for using payments for members

### PR DESCRIPTION
**Pull request by rjmk**
Hey, @ivanmauricio @JMurphyWeb! Does this look good for allowing us to reuse the payments table on the user site?

### CODE REVIEW

**Comment by ivan-unfolds** [comment]
@rjmk looks good. I did the following: 

```
var headers = [ 'Date', 'Description', 'Charges', 'Payments', 'Balance Due' ]
    .concat(remove_payment ? [ 'Reference', 'Notes', 'Delete' ] : [])
```

On the wireframe on the doc document Richard only shows these headers. I also think it will be too crowded on mobile view with any more. What do you think?

**Comment by ivan-unfolds** [comment]
You can see what I have done on the display-member-view-payments branch.

**Comment by jay-meister** [comment]
@ivanmauricio seems to have this covered in #323 Can we close this PR @rjmk ?

**Comment by rjmk** [comment]
:+1:

**Pull request closed without merging**
